# =============================
# DEPRECATED FILE (July 2025)
# This file is deprecated. See workers/DEPRECATED.md for details, actionable guidance, and references.
# Do not use for new development. For more information, see InjectMCP Prompt Section 1, 3, 4, and 5.
# References: Cloudflare, 2024; Mozilla, 2024.
# =============================
# Wrangler configuration for Cloudflare Worker environment variables
# Place this in your project root as wrangler.toml

name = "cloudflare-smart-cache"
main = "workers/cf-smart-cache-html.js"
type = "javascript"

[vars]
CLOUDFLARE_EMAIL = "your-email@example.com"
CLOUDFLARE_API_KEY = "your-global-api-key"
CLOUDFLARE_ZONE_ID = "your-zone-id"

# For local development, create a .dev.vars file (do NOT commit secrets):
# CLOUDFLARE_EMAIL=your-email@example.com
# CLOUDFLARE_API_KEY=your-global-api-key
# CLOUDFLARE_ZONE_ID=your-zone-id
